---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: install httpd on red hat servers
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "RedHat"

  - name: add php support for httpd
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "RedHat"