---

- hosts: all
  become: true
  tasks:

  - name: update repository index on ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 on ubuntu servers
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache2
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"