---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: remove apache2 from ubuntu servers
    apt:
      name: apache2
      state: absent

  - name: remove php support from ubuntu servers
    apt:
      name: libapache2-mod-php
      state: absent