### install apache2 on ubuntu and httpd on RedHat and php on both ###

- name: install apache2 on ubuntu and httpd on RedHat and php on both
  tags: apache2,httpd,apache,php
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

### start and enable apache service ###

- name: start and enable apache service
  tags: httpd,apache
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

### change email address for RedHat admin ###

- name: change email address for RedHat admin
  tags: apache2,httpd,apache
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin shimerasaf111@gmail.com
  when: ansible_distribution == "RedHat"
  notify: restart_apache
  
### copy html file on servers ###

- name: copy html file
  tags: apache2,httpd,apache
  copy:
    src: ~/Desktop/ansible/learn-linux-tv/ansible-01/files/default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644